import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "hello",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          {" "}
          <p>Header</p>
        </header>
        {children}
      </body>
    </html>
  );
}
